### ISSUE TITLE
Trendnet Setup?

### ISSUE THREAD

**Issue by cmaloney7** [amiracle/homemonitor#10]
Trying to get this to work for my TRENDnet TEW‑812DRU wireless router, but can't seem to get Splunk to read the syslog.  Any hints?

**Comment by amiracle** [comment]
Can you post a copy of the syslog output from the router?

**Comment by amiracle** [comment]
Some routers don’t act like firewalls and so the data that comes out of them will not work for this app. It is recommended that you get a router/firewall that gives you network data (source, destination etc.) which will populate the app. 

Please open a new issue if you run into further problems.
