### ISSUE TITLE
pfsense 2.4.1

### ISSUE THREAD

**Issue by repomanz** [amiracle/homemonitor#11]
Hi - just wonder if this splunk app is still under development.  I'm on pfsense 2.4.1 and most if not all of the dashboards and data are not functioning.

**Comment by amiracle** [comment]
I am still developing this app and I have it working with my pfSense firewall running 2.4.1.  I ended up having my pfsense firewall send directly to a syslog server and then I used a Splunk Universal Forwarder to send the data into my indexer.

**Comment by repomanz** [comment]
Do you have some documentation regarding 2.4.1 and home monitor configuration you can share with me?

**Comment by repomanz** [comment]
** bump **

I have the application installed but when i go to dashboards is doesn't show many any sourcetypes to pick in the drop down.   I confirmed that i have both the syslog coming over from pfsense.  Additionally my device type is set as pfsense in the configuration.

Do you have some setup documentation on this i can review?

**Comment by aauf** [comment]
Hi Amiracle.
Is it possible to contribute to your project? There are pull requests pending and I am therefore not sure.

**Comment by repomanz** [comment]
guessing this closed? No response (17 days)

**Comment by rftiiv15** [comment]
Bandwidth .bat file does not work right. I had to edit input.conf and configure it to use the python script.

**Comment by amiracle** [comment]
The windows batch file does not work, I’ve been trying to have it use the same python script I have for Linux.

**Comment by amiracle** [comment]
This app does work with pfsense 2.4.1 and it’s been tested with the latest version of pfsense 2.4.2 p1.
